/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\landing-page-opt.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/landing-page-opt.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={22.895} position={[7.359, 1.338, 6.926]} rotation={[0.065, 0.814, -0.047]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.004']} position={[0, 1.59, 0]} />
      <mesh geometry={nodes.base.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.rock1.geometry} material={materials.Material} position={[-1.15, 1.789, 1.849]} scale={[0.229, 0.495, 0.236]} />
      <mesh geometry={nodes.rock3.geometry} material={materials['Material.003']} position={[2.436, 1.507, 0.155]} rotation={[0, 0, -Math.PI / 9]} scale={[0.229, 0.523, 0.236]} />
      <mesh geometry={nodes.rock2.geometry} material={materials['Material.001']} position={[-0.979, 1.712, -1.745]} rotation={[-0.175, 0, 0]} scale={[0.229, 0.523, 0.236]} />
    </group>
  )
}

useGLTF.preload('/landing-page-opt.glb')
