/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\landing-page.glb 
*/

import React from 'react';
import { useGLTF, PerspectiveCamera, Sparkles } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';

import { EffectComposer, Bloom } from '@react-three/postprocessing';

export function Cube(props) {
  const meshRef = useRef();
  const meshRock1Ref = useRef();
  const meshRock2Ref = useRef();
  const meshRock3Ref = useRef();

  useFrame(({ clock }) => {
    // Animate rotation based on time
    meshRef.current.rotation.x = clock.elapsedTime * 0.2;
    meshRef.current.rotation.y = clock.elapsedTime * 0.1;

    // Animate position with a sine wave for a "floating" effect
    meshRef.current.position.y = Math.sin(clock.elapsedTime) * 0.1 + 1.59;
    meshRock1Ref.current.position.y = Math.sin(clock.elapsedTime) * 0.3 + 1.53;
    meshRock2Ref.current.position.y = Math.sin(clock.elapsedTime) * 0.2 + 1.57;
    meshRock3Ref.current.position.y = Math.sin(clock.elapsedTime) * 0.5 + 1.51;
  });

  const { nodes, materials } = useGLTF('/landing-page.glb');
  return (
    <group {...props} dispose={null} {...props}>
      <group ref={meshRef} position={[0, 1.59, 0]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.Monggo} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Express} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.React} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials.Node} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials.Redux} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials.Tailwind} />
      </group>
      <mesh geometry={nodes.base.geometry} material={materials['Material.002']} />
      <mesh
        ref={meshRock1Ref}
        geometry={nodes.rock1.geometry}
        material={materials.Material}
        position={[-1.15, 1.789, 1.849]}
        scale={[0.229, 0.495, 0.236]}
      />
      <mesh
        ref={meshRock3Ref}
        geometry={nodes.rock3.geometry}
        material={materials['Material.003']}
        position={[2.436, 1.507, 0.155]}
        rotation={[0, 0, -Math.PI / 9]}
        scale={[0.229, 0.523, 0.236]}
      />
      <mesh
        ref={meshRock2Ref}
        geometry={nodes.rock2.geometry}
        material={materials['Material.001']}
        position={[-0.979, 1.712, -1.745]}
        rotation={[-0.175, 0, 0]}
        scale={[0.229, 0.523, 0.236]}
      />
      {/* added */}
      <Sparkles
        color="rgba(114, 255, 208, 1)"
        noise={10}
        speed={0.1}
        opacity={1}
        position={[0, 1.5, 0]}
        scale={[2, 2, 2]}
        count={200}
      />
      <Sparkles
        color="rgba(114, 255, 208, 1)"
        count={500}
        speed={0.1}
        opacity={0.5}
        position={[0, 2, 0]}
        scale={[18, 5, 15]}
        noise={1}
      />
      <EffectComposer stencilBuffer={true}>
        <Bloom luminanceThreshold={0.01} intensity={0.08} />
      </EffectComposer>
    </group>
  );
}

useGLTF.preload('/landing-page.glb');
