name: Docker Image CI

on:
  push:
    branches: ['feature/**']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "danibanez09" --password-stdin
          docker image build -t 'portfolio/frontend:${{ steps.date.outputs.date }}-${{ steps.vars.outputs.sha_short }}' .
      - name: Push Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "danibanez09" --password-stdin
          docker push 'portfolio/frontend:${{ steps.date.outputs.date }}-${{ steps.vars.outputs.sha_short }}'
